services:
  mysql:
    image: mysql:8.4.7

    container_name: mysql_container
    ports:
      - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=senha
      # - MYSQL_DATABASE=db
    restart: always
